version: 2
updates:
  - package-ecosystem: composer
    directory: /upload/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - php

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
