# These are supported funding model platforms

ko_fi: devcraft
custom: ['https://paypal.me/MaximH', 'https://sobe.ru/na/devcraftclub', 'https://yoomoney.ru/to/41001454367103', 'https://www.donationalerts.com/r/maharder', 'https://devcraft.club/donate/drives/na-chaj.1/']
