name: Ошибка
description: Сообщить об ошибке / баге
title: "[Ошибка]: "
assignees:
    - Gokujo
labels:
    - bug
body:
    -   type: markdown
        attributes:
            value: |
                Спасибо, что нашли время, чтобы составить этот отчёт.
    -   type: checkboxes
        id: prechecks
        attributes:
            label: Предварительные проверки
            options:
                -   label: Я прочёл / прочла [пользовательское соглашение](https://devcraft.club/pages/licence-agreement/) и согласен / согласна с ним
                    required: true
                -   label: Я ознакомился / ознакомилась с [документацией](https://readme.devcraft.club/dev/dle_api/)
                    required: true
                -   label: Я проверил / проверила, что такая проблема ещё не открыта в [очереди тикетов](https://devcraft.club/tickets/queue?status_not%5B0%5D=-1)
                    required: true
    -   type: textarea
        id: what-happened
        attributes:
            label: В чём проблема?
            description: Опишите проблему в деталях. Если возможно — пошагово, как её воспроизвести.
            placeholder: Описание проблемы
        validations:
            required: true
    -   type: textarea
        id: what-should-happen
        attributes:
            label: Что ожидали?
            description: Что должно было произойти вместо ошибки?
            placeholder: Ожидаемое поведение
        validations:
            required: false
    -   type: input
        id: plugin-version
        attributes:
            label: Версия плагина
            description: Указана в менеджере плагинов DLE или в DevCraft Admin → DLE API
        validations:
            required: true
    -   type: dropdown
        id: dle-version
        attributes:
            label: Версия DLE
            options:
                - "20.0"
                - "17.x"
                - "16.x"
        validations:
            required: true
    -   type: dropdown
        id: php-version
        attributes:
            label: Версия PHP
            options:
                - "8.3"
                - "8.2"
                - "8.1"
        validations:
            required: true
    -   type: textarea
        id: screenshots
        attributes:
            label: Скриншоты
            description: Если есть возможность, добавьте скриншоты
        validations:
            required: false
    -   type: textarea
        id: logs
        attributes:
            label: Логи / ответ API
            description: Если ошибка связана с HTTP-запросом — вставьте тело ответа и HTTP-статус
            render: json
        validations:
            required: false
